version: "3.9"

volumes:
  redis-cache-volume:
    driver: local

services:

  redis-cache:
    image: redis:latest
    restart: always
    container_name: redis-cache
    ports:
      - 6379:6379
    volumes:
      - redis-cache-volume:/data
